### ISSUE TITLE
Color-coded borders for guild upgrades

### ISSUE THREAD

**Issue by queicherius** [gw2efficiency/issues#1715]
> Color-coded borders for guild upgrades. The top is dark mode, bottom light, and it is very difficult to tell the difference between completed and available upgrades in dark mode. Something simple would be fine, even a 1px green border for completed upgrades.

![image](https://github.com/gw2efficiency/issues/assets/4615516/357e179c-5da8-4ac4-969e-03935272d0fd)

**Comment by queicherius** [comment]
Works in the overview, but not in the details:

![image](https://github.com/gw2efficiency/issues/assets/4615516/d9dc76a6-2124-4443-ac08-1ce542d70e18)
![image](https://github.com/gw2efficiency/issues/assets/4615516/c87146cb-3444-48ef-80d0-8838d701b183)

**Comment by Ecmelt** [comment]
Fixed.

**Comment by xvwyh** [comment]
This messes up the layout of upgrades everywhere, since now completed and not-completed elements have different size:
![image](https://github.com/gw2efficiency/issues/assets/43143822/7bc2425b-b0d7-4690-aef7-14be7361321f)
![image](https://github.com/gw2efficiency/issues/assets/43143822/62f750cc-9c5f-4368-8949-f799df22e4ae)
![image](https://github.com/gw2efficiency/issues/assets/43143822/a1ec8c23-08e9-4727-a232-18b2a663de5f)
![image](https://github.com/gw2efficiency/issues/assets/43143822/209c4069-b78b-49fa-b340-cc361f71bb65)
![image](https://github.com/gw2efficiency/issues/assets/43143822/1da6c089-2115-4d3b-a0ac-95c79bfac451)

Give non-completed elements a border with transparent color but the same thickness. And reduce the margin between elements from 5px to 3px (1px in details view, since the border there is 1+3px) to account for the size increase, so that the same number of elements would fit in a row as before.

```css
.guild-wrapper .side-content.upgrades .upgrade-list li {
    ...
    border: 1px solid transparent;
    margin-right: 3px;
    margin-bottom: 3px;
}

.guild-wrapper .side-content.building .upgrade-selection .upgrade-list li {
    ...
    border: 1px solid transparent;
    border-right: 3px solid transparent;
    border-bottom: 3px solid transparent;
    margin-right: 1px;
    margin-bottom: 1px;
}
```

**Comment by Ecmelt** [comment]
Alright, changed margins to 3px for both. Added overflow: hidden for .building so can use same structure there instead since 1px margins make elements way too close. I'll not close this till i know it works as intended.

**Comment by xvwyh** [comment]
Looks good on the "Upgrades" page, but the layout is still broken on "Notary", "Tavern" and other subpages **with <100% zoom**.
![image](https://github.com/gw2efficiency/issues/assets/43143822/ebcc82b5-996c-4ecf-908f-ebc89be44e0a)
![image](https://github.com/gw2efficiency/issues/assets/43143822/e98716bf-5e50-47c5-b0a5-c3323c04931c)
I'm guessing this is because the contents of each container add up to exactly 250px, and the container itself having a fixed width of 250px, but on non-100% zoom, due to floating point precision errors or rounding, the contents get ever so slightly larger than 250px and start overflowing.

I'm not sure what you were trying to achieve with "overflow: hidden", it makes no visual difference for me. Just expand the container elements from 250px to 260px to account for each of the 5 elements in the row being inflated by 1px from each side, to maintain the same buffer in the container as it used to have before the borders got added:

```css
.guild-wrapper .side-content.building .upgrade-selection
{
    ...
    width: 260px;
}

.guild-wrapper .side-content.building .upgrade-selection .upgrade-list
{
    ...
    max-width: 260px;
}
```

->
![image](https://github.com/gw2efficiency/issues/assets/43143822/fc0cb42e-34bf-4e49-83dd-4fa2d952d4fe)
![image](https://github.com/gw2efficiency/issues/assets/43143822/20d8735f-25aa-40d5-8ccc-2f080f1ce39a)
